name             'role_proxy'
maintainer       'Christian A. Rodriguez & Leandro Di Tommaso'
maintainer_email 'chrodriguez@gmail.com leandro.ditommaso@mikroways.net'
license          'MIT'
description      'Installs/Configures role_proxy'
long_description 'Installs/Configures role_proxy'
version          '0.1.0'

depends 'mo_application'
depends 'varnish'
